### ISSUE TITLE
Need your opinion, for your ps5-payloads-sdk

### ISSUE THREAD

**Issue by logic-68** [john-tornblom/ps5-payload-sdk#3]
Good morning, John
I mpe allow to contact you.
I have a Digital 4.03. I want to use your environment. I tried to transcribe your getfsstat or nmout. For me as for other Devs. However with other environments this was not possible. Yesterday I wanted to dump my own .sprx .elf... again a failure. I got info, opinions from other Devs. It is often related failures it seems to Webkit or Digital. Can you tell me if this is indeed a lost cause. Or if I can continue to think that we can port nmout, -ps5-self-dumper to the Digital? We removed CPU_2 to no avail.
 We do use dbg but it seems inactive at the time of the Dump. I am aware of the procedure but without my sprx decrypt I could not use your environment. Of course I am willing to share my files for you or any other Devs to advance your work. But unfortunately I have not yet succeeded in Dumper. Could you exchange some information on this subject? 
Thank you, see you soon and all my best wishes for this new year. Regards
(sorry for my english!)

**Comment by john-tornblom** [comment]
As far as I know, nmount() is only available in libkernel_sys. The webkit browser on the ps5 is linked with libkernel_web (rather than libkernel_sys), which does not include nmount(). I can't say much about the possibility to run the ps5-self-dumper on your machine, check with its author.

Regarding sharing your code, please consider sharing it in public. I do, and I expect any derived work to do the same.
